Update dailook司洛.yml
修改文件解决报错

diff --git a/.github/workflows/dailook司洛.yml b/.github/workflows/dailook司洛.yml
--- a/.github/workflows/dailook司洛.yml
+++ b/.github/workflows/dailook司洛.yml
@@ -1,5 +1,3 @@
-
-
 #
 # https://github.com/P3TERX/Actions-OpenWrt
 #
@@ -103,6 +101,21 @@ jobs:
       if: (!cancelled())
       run: df -hT
 
+    - name: Verify firmware directory before upload
+      run: |
+        if [ ! -d "$GITHUB_WORKSPACE/openwrt/bin" ] || [ ! "$(ls -A $GITHUB_WORKSPACE/openwrt/bin)" ]; then
+          echo "Error: No files found in firmware directory."
+          exit 1
+        fi
+        echo "Firmware directory exists and contains files."
+
+    - name: List contents of firmware directory before upload
+      run: |
+        echo "Listing files in firmware directory:"
+        ls -lh ${{ env.FIRMWARE }}
+        echo "Firmware directory size:"
+        du -sh ${{ env.FIRMWARE }}
+      
     - name: Upload bin directory
       uses: actions/upload-artifact@main
       if: steps.compile.outputs.status == 'success' && env.UPLOAD_BIN_DIR == 'true'
